apiVersion: v1
kind: Pod
metadata:
  name: tompod
  labels:
    app: javaapp
spec:
  containers:
    - name: tomdeploy
      image: myydocker143/pushes:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          protocol: TCP

