apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  label:
    env: prod
    app: javaapp
spec:
  containers:
    - name: firstcontainer
      image: firstimage
      ports:
        - containerport: 80
