apiVersion: v1
kind: Service
metadata:
  name: javaapp
  labels:
    name: javaapp
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080

